### PR TITLE
feat: worker deploy and delete

### PR DESCRIPTION
**Pull request by gentlementlegen**
Adds automatic deploy and delete for the worker for branches.

### CODE REVIEW

**Comment by 0x4007** [comment]
There is a spec for this what is the context?

**Comment by gentlementlegen** [comment]
@0x4007 I added this to the plugin template, but didn't sync it to all our Worker plugins. We don't have the automated sync yet, and this will help targeting development branch for plugins as well.

**Comment by 0x4007** [comment]
Oh I just realized this is your new feature to host a separate worker for every branch! As long as you tested it works then I can approve.

**Comment by gentlementlegen** [comment]
@0x4007 Of course:
- [deploy run](https://github.com/Meniole/command-wallet/actions/runs/10775998870)
- [delete run](https://github.com/Meniole/command-wallet/actions/runs/10776082203)

**Pull request merged**
